### ISSUE TITLE
[用户友好] Address Book缺少一些功能

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#1]
1. 缺少复制按钮；
2. 缺少热区进入编辑的功能
3. Address Book

![截屏2021-07-22 下午2 44 19](https://user-images.githubusercontent.com/39148294/126599568-4e405cd0-d389-4e1d-8277-61d3d0314abe.png)

**Comment by xie-yue** [comment]
@sunjeon @yating-900 复制需要添加
编辑的功能已经加进去了

**Comment by sunjeon** [comment]
编辑的功能加的地方是？ 我好像没找到。

**Comment by xie-yue** [comment]
@sunjeon UI的设计是往左边滑动

**Comment by steven1227** [comment]
已测。可以左滑编辑
