### ISSUE TITLE
【MO】定价出售-二次确认弹窗

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#106]
第一个红框改为“出售价格”
第二个红框内容删除
出售时间的单位修改
二次确认弹窗，把上架方式选择的部分（蓝框）去除
<img width="664" alt="截屏2022-01-12 下午2 33 10" src="https://user-images.githubusercontent.com/87798080/149076232-8c19220c-0065-4b59-9085-3e8c16af9994.png">

**Comment by evan0412** [comment]
fixed

**Comment by FamelessLeo** [comment]
第二个蓝框，出售时间这个没有去掉～
