### ISSUE TITLE
[IOS iPhone 12 Pro] Send界面

### ISSUE THREAD

**Issue by zifanwangsteven** [steven1227/MovieDB#11]
* Amount 输入会报错 ![IMG_4524 2](https://user-images.githubusercontent.com/57160817/126759320-c0dc2b46-33da-49ec-b3dc-ed2e18200abb.PNG)
* To 点击页面会上弹一下但键盘没有弹出![IMG_4525](https://user-images.githubusercontent.com/57160817/126759709-9fb480cc-6307-4eb5-a1ce-7a5bad26654c.PNG)
* To 点击失败后再点击scan 或address book 都会报错 ![IMG_4523 2](https://user-images.githubusercontent.com/57160817/126759328-5de7ea59-951f-4f82-a585-027b814479fb.PNG)
* Gas输入会报错 ![IMG_4522 2](https://user-images.githubusercontent.com/57160817/126759331-01b657f4-7103-4e8e-9851-954438328e1a.PNG)

**Comment by sunjeon** [comment]
已解决
