### ISSUE TITLE
【MO】在上架/拍卖等待的过程中，关闭弹窗后应该上架按钮置灰，不可点击；下架也是如此

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#117]
![截屏2022-01-12 下午2 37 16](https://user-images.githubusercontent.com/87798080/149076625-02559e85-df01-41eb-afd0-6cd5b404df95.png)

**Comment by ShaySong99** [comment]
这里disable态无确定状态，页面刷新后同样可以点击操作

**Comment by FamelessLeo** [comment]
如果刷新的话就算了，正常情况应当置灰按钮避免误操作

**Comment by ShaySong99** [comment]
todo 手机端页面一起
