### ISSUE TITLE
【MO】大小写字母统一规范

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#118]
![1641969466016](https://user-images.githubusercontent.com/39148294/149076694-dda7d6e5-faa2-47ab-b6df-f8beaeb172f0.jpg)
<img width="822" alt="截屏2022-01-12 下午2 38 25" src="https://user-images.githubusercontent.com/39148294/149076734-06f522da-7908-45e9-a330-e761e0903582.png">

**Comment by evan0412** [comment]
fixed

**Comment by FamelessLeo** [comment]
红框内改为“You will unlist”
蓝框内改为“Time left”
![image](https://user-images.githubusercontent.com/87798080/149488227-845cbdc4-c1ea-43c0-abcb-ed4b2fbbce00.png)
