### ISSUE TITLE
【MO】取消上架之后我的历史会清空

### ISSUE THREAD

**Issue by cloud8little** [steven1227/MovieDB#124]
上架一个NFT，在没人出价或者没人买的时候取消上架，再次点进该NFT

![7b4a15b97fcbd5c7cf42555f01e71b7](https://user-images.githubusercontent.com/34291844/149259124-e31c6250-588e-480b-acb2-419c1221a749.png)

![e36c99cafb7d5c60a13547aa85a60f7](https://user-images.githubusercontent.com/34291844/149259271-4ca371b2-cedc-45ae-b145-e9921681121d.png)

打开“我的历史”

![7047e0e0e29138b1a73d977f9381505](https://user-images.githubusercontent.com/34291844/149264352-3e22f122-d190-4c20-b62f-8d1f7a648606.png)

**Comment by ShaySong99** [comment]
待详细描述 是否是重新刷新页面
