### ISSUE TITLE
【MO】挂单使用FLM结算没有抓到FLM的价格

### ISSUE THREAD

**Issue by superboyiii** [steven1227/MovieDB#126]
![1642057020(1)](https://user-images.githubusercontent.com/38493437/149280698-c83501d4-35b4-458a-be1e-7c0539d95404.png)
![1642058106(1)](https://user-images.githubusercontent.com/38493437/149283114-ef7a4c1e-8505-4efe-a7fe-d035c4490218.png)

**Comment by ShaySong99** [comment]
测试网flm Hash和 正式网不一致，询价失败
