### ISSUE TITLE
【MO】取消上架之后的NFT不应出现提取按钮

### ISSUE THREAD

**Issue by cloud8little** [steven1227/MovieDB#129]
![75415db1deb6268bdb5577501fada71](https://user-images.githubusercontent.com/34291844/149287359-24cae10a-c9b7-4bc5-8656-1ee5afc9ea82.png)

**Comment by ShaySong99** [comment]
这个是否是拍卖上架，已过期的状态？ 那这时是应该cancel list 还是 claim 操作

**Comment by FamelessLeo** [comment]
拍卖和上架到期后，需要用户进行下架操作才能回到自己钱包，这里应该显示下架（Unlist）

**Comment by ShaySong99** [comment]
todo 手机端页面一起
