### ISSUE TITLE
【MO】价格位数较多时，在框内换行

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#134]
![截屏2022-01-14 上午11 26 47](https://user-images.githubusercontent.com/87798080/149472441-2b08f335-5dfe-4b05-8661-9cc7c58b7386.png)

**Comment by steven1227** [comment]
PR create

**Comment by cloud8little** [comment]
![7f08ce8b6f31e315e6f1231df00f0bc](https://user-images.githubusercontent.com/34291844/149717119-2ddade0b-2603-4504-af82-cd1000d6b2dd.png)
