### ISSUE TITLE
【MO】在数字输入框内可以输入e，但不能输入其他英文，应当只能输入数字

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#135]
![截屏2022-01-14 上午11 12 52](https://user-images.githubusercontent.com/87798080/149446677-0d8c2bd5-3c34-457d-a724-86497758c591.png)

**Comment by steven1227** [comment]
https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in
