### ISSUE TITLE
改进 Records 的Asset

### ISSUE THREAD

**Issue by WSbaikaishui** [steven1227/MovieDB#14]
####                                                                                                                                                                    安卓 小米11  张耀文
![Screenshot_2021-07-23-17-00-25-925_com onegate](https://user-images.githubusercontent.com/46080358/126760050-3a8aa835-bc56-45ff-9c41-2d14b80b8074.jpg)

**Comment by sunjeon** [comment]
赞同。

**Comment by yating-900** [comment]
<img width="750" alt="Screenshot 2021-07-26 at 11 56 18" src="https://user-images.githubusercontent.com/15194857/126931055-49ee9de0-59a1-4ff8-a205-1deab51c3896.png">

嗯嗯 这个usability issue 可以优化下
