### ISSUE TITLE
【MO】一级市场购买后，在二级市场及刘的艺术家页面看到不对应NFT

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#146]
![截屏2022-01-17 下午5 17 53](https://user-images.githubusercontent.com/87798080/149741765-103d32f6-dbad-45c9-bc4e-a5479eb4a91e.png)

**Comment by ShaySong99** [comment]
fura问题

**Comment by ShaySong99** [comment]
接口
