### ISSUE TITLE
【MO】一级市场某一种NFT售罄后，页面直接不显示了，应当显示原来的购买页面，按钮置灰，显示“已售罄”

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#149]
![截屏2022-01-17 下午5 33 03](https://user-images.githubusercontent.com/87798080/149744195-0832ffab-78ab-4fc1-9f2f-cf8f9d05489b.png)

**Comment by ShaySong99** [comment]
fixed
