### ISSUE TITLE
[IOS iPhone12 Pro] Wallet页面余额不刷新

### ISSUE THREAD

**Issue by zifanwangsteven** [steven1227/MovieDB#15]
已从faucet claim 500 GAS 可查到，但页面余额不刷新
![IMG_4529](https://user-images.githubusercontent.com/57160817/126760839-c71ad00c-3347-4730-a47d-974ad8973551.PNG)

**Comment by xie-yue** [comment]
record是有时间的，可能是时间限制问题，另外在confirm的状态这个页面需要手动刷新，本地无法再现，请确认下操作流程

**Comment by xie-yue** [comment]
@zifanwangsteven
