### ISSUE TITLE
这边能不能限制下钱包名字只能用字母和数字或者-等符号，感觉这样容易注入代码，而且不太美观

### ISSUE THREAD

**Issue by lutianzhou001** [steven1227/MovieDB#16]
![IMG_7294](https://user-images.githubusercontent.com/6642040/126760846-af06c44a-67fd-4ebb-96c6-35850e454526.PNG)

**Comment by sunjeon** [comment]
暂时还是认为：可以随便用户定义。比如想起个二次元的名字之类的。日语 阿拉伯语 各种个性化名字都可以。因为这个是给用户自己看的。他自己认可就好。
