### ISSUE TITLE
【MO】我的NFT下，左侧筛选栏增加“未领取”选项

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#163]
![截屏2022-01-24 上午10 53 10](https://user-images.githubusercontent.com/87798080/150714433-c00a746d-0ebf-4704-8fca-7b72ec249bb4.png)

**Comment by cloud8little** [comment]
![68ef3eb6b19ecc09999c2dab161bd6e](https://user-images.githubusercontent.com/34291844/151094936-ab64b8d1-89ab-4193-960d-24b559693d69.png)
