### ISSUE TITLE
【MO】按 最新上架 排序，排序不对

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#168]
![7554d073fd1b30e678bd0eebb73f082](https://user-images.githubusercontent.com/12728872/150925079-365f2b0b-ae53-4b10-a03e-9189884378b7.png)

**Comment by superboyiii** [comment]
![image](https://user-images.githubusercontent.com/38493437/150925480-7e955618-bc4e-436a-93b8-bed1c0a4d1b5.png)
![1643093240(1)](https://user-images.githubusercontent.com/38493437/150925582-cb320a94-36a2-48ee-8108-f8720e853177.png)
