### ISSUE TITLE
[改进] 产品改进

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#17]
1. Transaction Details页面的 TXID 旁增加“复制”按钮

![741627031762_ pic](https://user-images.githubusercontent.com/39148294/126761881-36877af0-05c8-46e2-a076-3b909b052e00.jpg)

**Comment by sunjeon** [comment]
麻烦yating加一下

**Comment by xie-yue** [comment]
在展开的时候添加

**Comment by yating-900** [comment]
<img width="625" alt="Screenshot 2021-07-26 at 11 53 00" src="https://user-images.githubusercontent.com/15194857/126930822-93d9f561-4d13-40a1-8fef-ba43a6212765.png">

如图, txid这里添加一个“copy” 按钮。

**Comment by xie-yue** [comment]
@yating-900 那么现在txid展开的功能就去掉吧

**Comment by yating-900** [comment]
> @yating-900 那么现在txid展开的功能就去掉吧

展开的功能是指分两行显示吗？

**Comment by sunjeon** [comment]
？ txid应该跳转到外部页面。

刚看了下，现在做成了点击txid的一长串字母也是复制功能。需要改进。

**Comment by sunjeon** [comment]
🤔 这个issue现在是被挪到合集里面了还是结束了？ @yating-900

**Comment by yating-900** [comment]
> 🤔 这个issue现在是被挪到合集里面了还是结束了？ @yating-900

嗯 这个合集里也提到了

**Comment by sunjeon** [comment]
ok
