### ISSUE TITLE
【V】NFT Name 长度超出

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#177]
![image](https://user-images.githubusercontent.com/12728872/157154531-0791b874-4cef-4278-86f1-2df4562bb7a8.png)

**Comment by ProDog** [comment]
貌似问题还在 @xie-yue 
![image](https://user-images.githubusercontent.com/12728872/158097306-4fd79de0-2f94-4700-bdbd-1bdc3dfa2a91.png)

**Comment by xie-yue** [comment]
改短了
