### ISSUE TITLE
一笔转账，手续费扣除和转账金额在record里面分成了两笔交易

### ISSUE THREAD

**Issue by superboyiii** [steven1227/MovieDB#18]
一笔转账，手续费扣除和转账金额在record里面分成了两笔交易
并且手续费扣除的那个记录生成了一个空的txid，这个是不对的。其实是同一笔交易。
![image](https://user-images.githubusercontent.com/38493437/126762290-39d517b4-9756-4ddd-be5a-c15a9d69f346.png)
![image](https://user-images.githubusercontent.com/38493437/126762900-b72bf2dd-5db6-4faa-a688-081e751696b3.png)

**Comment by xie-yue** [comment]
需要和服务端商量

**Comment by sunjeon** [comment]
请参考55#的解决方案。本issue关闭。
