### ISSUE TITLE
【V】切换网络需要重新输入密码

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#182]

**Comment by sunjeon** [comment]
测试网和主网互相切换时，应该改为：不需要重新输入密码。

**Comment by ProDog** [comment]
现在不需要重新输入密码了，但是切换网络的时候页面窗口会先变成一个小方块，切换完成再恢复成正常，建议窗口不变的情况下进行切换。参考 metamask 。

![image](https://user-images.githubusercontent.com/12728872/158499341-20e294a7-e58f-4186-8734-d9b6714a9ca6.png)
