### ISSUE TITLE
【V】交易记录一直转圈 加载不出来

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#183]
![image](https://user-images.githubusercontent.com/12728872/157159399-0c9646aa-3669-4880-a6cd-53a846658770.png)

**Comment by sunjeon** [comment]
给一个timeout的文案和icon，不仅仅是这个页面，适用于全部2(?)分钟后，数据读取失败的方案。@谢越，其余数据超时读取error的页面也请更新
![截屏2022-03-14 14 45 51](https://user-images.githubusercontent.com/39148294/158119111-e4fe73d6-7441-49ab-829c-bfa7fa47b5fe.png)
。

**Comment by xie-yue** [comment]
给了一个加载失败的页面，但是触发条件比较苛刻，思考下怎么触发。。

**Comment by ProDog** [comment]
转了2分钟也没出来失败页面。

**Comment by xie-yue** [comment]
重新给了一个统一的通信失败页面，可以通过加载时关闭网络来测试
