### ISSUE TITLE
【V】Remove Wallet 的文案和 Export Private Key 的一样

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#184]
![image](https://user-images.githubusercontent.com/12728872/157160713-1d033105-30e5-404d-8e79-4cc251ebf926.png)

**Comment by sunjeon** [comment]
<img width="581" alt="截屏2022-03-10 下午3 26 39" src="https://user-images.githubusercontent.com/39148294/157610276-a120e41a-4667-44f7-a3c4-6d0ad8935e92.png">

**Comment by sunjeon** [comment]
1. 导出recovery phrase 的文案修改：
标题： Do not share your recovery phrase to anyone!
内容：If someone has your recovery phrase they will ...(同上)

2. Remove Wallet 的文案修改：
标题：Remove all my wallets!
内容：This will delete all your active wallets. Make sure you have your recovery phrase or private key backed up.
