### ISSUE TITLE
【V】增加在浏览器查看该地址的功能

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#186]

**Comment by sunjeon** [comment]
可以加
![截屏2022-03-14 14 33 48](https://user-images.githubusercontent.com/39148294/158117600-33c06e6e-634d-4ebc-a06c-ea63f2289a75.png)
。

**Comment by ProDog** [comment]
加在这里了，确认一下可不可以

![image](https://user-images.githubusercontent.com/12728872/158726321-d7070048-f882-4638-831b-c6d7995e9910.png)

**Comment by xie-yue** [comment]
UI更新了
