### ISSUE TITLE
Address vaild

### ISSUE THREAD

**Issue by WSbaikaishui** [steven1227/MovieDB#19]
#### 安卓 小米11 张耀文
![Screenshot_2021-07-23-17-17-23-788_com onegate](https://user-images.githubusercontent.com/46080358/126762252-028a3be5-157f-4fbd-91e8-5ae3ba8e2032.jpg)

**Comment by chenzhitong** [comment]
复现步骤：

进到这个页面，先点击Address输入框，再点其它地方（这时触发格式校验，会显示 Invalid address），
再点扫码，这时Address输入框已经更新，但校验没有重新校验，仍然显示 Invalid address

建议，扫码后重新触发地址校验

**Comment by WSbaikaishui** [comment]
bug修复
