### ISSUE TITLE
【V】Swap 滑点过大时，钱包页面消失

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#190]
![image](https://user-images.githubusercontent.com/12728872/157182282-8274bbff-c6da-4337-affd-b1dbf25d3332.png)

如图，点击 Review Order，钱包会变成这样：

![image](https://user-images.githubusercontent.com/12728872/157182500-31179207-b088-4d1a-a7b1-c675cc7a6473.png)

**Comment by sunjeon** [comment]
神奇
