### ISSUE TITLE
【V】NFT 增加跳转至浏览器的功能

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#191]
鼠标放上去就会一直闪

![image](https://user-images.githubusercontent.com/12728872/157191630-18677168-8a7e-4792-9db1-00bbf49e987f.png)

**Comment by xie-yue** [comment]
禁用播放器，自动播放

**Comment by sunjeon** [comment]
+ 跳转至浏览器的功能。 
![截屏2022-03-14 14 30 35](https://user-images.githubusercontent.com/39148294/158117305-edba74d3-96d4-4834-b5f8-e9a8fb560151.png)

**Comment by xie-yue** [comment]
已添加

**Comment by ProDog** [comment]
建议这一级页面也增加在浏览器查看的功能，跳转至 Token Details 页面：

![image](https://user-images.githubusercontent.com/12728872/158503095-f3b00d91-816a-47e1-a3f5-69d8f88fab98.png)
