### ISSUE TITLE
【V】Assets List 会自动消失

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#194]
刚切换到这个地址时可以看见 Assets，过一会又消失了，显示所有资产都不在 Assets List 中

![image](https://user-images.githubusercontent.com/12728872/157198581-da19d243-e234-45db-a449-a27bdc4a10e9.png)

**Comment by ProDog** [comment]
GAS NEO bNEO FLM 这些应该默认都在 Assets List 中

**Comment by xie-yue** [comment]
服务器获取失败，错误后列表不显示
