### ISSUE TITLE
【V】Transfer 页面 To 应该在 Amount 前面

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#196]
![image](https://user-images.githubusercontent.com/12728872/157581134-32d94191-1c9c-4a3a-b57d-60b233065c44.png)

**Comment by sunjeon** [comment]
我个人感觉没有特别大的差异，所以之前就这样放了。刚去做了一个市场调研，发现确实这样做的项目比较多：
代币+数量+地址 的模式采用的有：FTX交易所；
代币+地址+数量 的模式采用的有：小狐狸；Onto；phantom；okex；binance；支付宝
地址+代币+数量：neoline

那我们就更改一下顺序为：
代币+地址+数量

请ui和前端修改一下排序。

**Comment by ProDog** [comment]
先填地址有助于计算网络费，To 地址不一样网络费可能不一样，但是 Amount 就不影响了。

**Comment by sunjeon** [comment]
基本转账手续费*1.2
