### ISSUE TITLE
【V】登录钱包时选择导入的跳转问题

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#197]
进入钱包时选择导入，提示删除所有钱包，选择 Delete All，又进入登录界面，开始循环....

![image](https://user-images.githubusercontent.com/12728872/158094808-6b7b9a7c-20b6-4466-aa77-f55e6b5f41d4.png)

![image](https://user-images.githubusercontent.com/12728872/158095207-ca78d64e-f716-4987-b0fb-fc476c7e9579.png)

**Comment by sunjeon** [comment]
删除所有钱包后，直接跳转网页 导入钱包页面。
