### ISSUE TITLE
改进 Manage Assets

### ISSUE THREAD

**Issue by WSbaikaishui** [steven1227/MovieDB#20]
#### 安卓 小米11  张耀文
![Screenshot_2021-07-23-17-26-13-570_com onegate](https://user-images.githubusercontent.com/46080358/126763007-7e6ed21c-9925-4f1f-bb80-6deadcf75be5.jpg)

**Comment by sunjeon** [comment]
正确展示为 +/-。请前端修改。

**Comment by xie-yue** [comment]
@yating-900 需要更新icon

**Comment by yating-900** [comment]
<img width="760" alt="Screenshot 2021-07-26 at 13 56 00" src="https://user-images.githubusercontent.com/15194857/126939855-24959c4a-3619-470d-ace4-e7c4533a2360.png">
目前的设计是除了neo和gas不能remove，其他的asset都有个“-”按钮来remove，如上图所示～

”-"  icon在iconfont里有，叫做“minor” @xie-yue 

p.s: 这里的“remove”应该只是移出观察列表吧, 自己的资产没有消失吧? @sunjeon 
感觉挺容易给用户造成误解...

**Comment by steven1227** [comment]
为在我这是 灰色的勾而不是 "-" icon 
![471627402532_ pic](https://user-images.githubusercontent.com/9437492/127189890-08c04237-a08e-47b9-8b5e-983eb8f0990e.jpg)

**Comment by sunjeon** [comment]
已验证
