### ISSUE TITLE
【V】文案错误

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#205]
This will remove your active wallet[s]。 wallet后面跟s

这个设计稿里面也错了。谢越麻烦你直接改一下吧。
![截屏2022-03-14 14 59 22](https://user-images.githubusercontent.com/39148294/158121126-4f873143-e2a7-41c7-83c5-c8438cd060d4.png)

**Comment by xie-yue** [comment]
这个remove只会移除一个当前钱包，确定要加复数？

**Comment by sunjeon** [comment]
不用。
