### ISSUE TITLE
【V】交易记录页面显示问题

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#208]
这是所有的 Recent Activity 页面

![image](https://user-images.githubusercontent.com/12728872/158315399-34bc0807-dcf9-4139-b145-1bbde298889f.png)

这是单个资产的 

![image](https://user-images.githubusercontent.com/12728872/158315587-a5dc1488-b0f6-4939-8f72-fbe0397222f5.png)

**Comment by sunjeon** [comment]
周一开会统一解决。

**Comment by xie-yue** [comment]
资产和NFT给了不同的宽度
