### ISSUE TITLE
加一个功能，一键删除地址信息

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#21]
涉及页面： 
1. Send的To输入框；
2. Add Address 的Address输入框
<img width="612" alt="WeChat79a8206a7c1222b77e80855a563ccedb" src="https://user-images.githubusercontent.com/39148294/126765738-db8f9191-1551-4786-b642-c8a9bb42c3d4.png">

**Comment by yating-900** [comment]
一般复制粘贴的话，地址不会出错吧，万一输错用户也可以全选后删除。
感觉一键删除的功能priority不是很高

**Comment by xie-yue** [comment]
@sunjeon 无论是qr还是地址簿，选择过后都会直接覆盖当前的输入，感觉删除功能必要性不大

**Comment by sunjeon** [comment]
那就不需要吧～
