### ISSUE TITLE
【V】修改密码不起作用

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#212]
修改过密码了，但用的一直还是旧密码

**Comment by ProDog** [comment]
修改密码后再次点击钱包就需要重新输入密码，但输入的依旧是旧密码；

修改密码后强制重新登录还是等下次点击钱包再重新登录？现在是下次点击钱包时重新登录，但这时候钱包也没有到自动锁定时间。

**Comment by sunjeon** [comment]
期待：修改密码后等自动锁定时间失效后，第一次点击钱包时，重新登录。在输入密码的登录页面，输入新密码，验证通过后 方可使用。

**Comment by sunjeon** [comment]
未重新登录前，选择【导出私钥】等需要输入密码的操作时。密码应该更新为新密码。

**Comment by sunjeon** [comment]
未重新登录前，选择【导出私钥】等需要输入密码的操作时。密码应该更新为新密码。
