### ISSUE TITLE
【V】切换地址后的显示问题

### ISSUE THREAD

**Issue by ProDog** [steven1227/MovieDB#213]
当在地址 A 的二维码页面切换到地址 B 时，页面依旧是地址 A 的二维码页面，资产页面也是同样的情况，切换地址后应该显示所有资产页：

![image](https://user-images.githubusercontent.com/12728872/158505627-58906af3-0bb7-4af0-9f6d-0f48eef8ee2f.png)

**Comment by ProDog** [comment]
NFT 页面，发送页面也是这样

**Comment by ProDog** [comment]
问题依旧存在

**Comment by xie-yue** [comment]
强制跳转主页面
