### ISSUE TITLE
【V】钱包总价值这个数值需要全部展示

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#214]
现状：不知道钱包里面有多少钱
期待：钱包总价值这个数值需要全部展示。省略不太好，超过边界值字体变小也行，hover展示全部也行。 一定要展示全部价值。
![截屏2022-03-16 10 47 54](https://user-images.githubusercontent.com/39148294/158506709-9706041d-940f-4fef-a6de-79c7c998c6ac.png)

**Comment by xie-yue** [comment]
hover

**Comment by ProDog** [comment]
还是没显示全：

![image](https://user-images.githubusercontent.com/12728872/158975162-12bbf4ee-f87f-4170-b5da-0ab1f6233c4c.png)
