### ISSUE TITLE
【V】输入内容左起

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#216]
现状：这边的输入框现在是从右边开始输入。
期待：左起输入。
![image](https://user-images.githubusercontent.com/39148294/158507494-3fc1404c-f7f5-4897-ada8-d721ecf4984e.png)

**Comment by ProDog** [comment]
Swap 页面还在右边

**Comment by ProDog** [comment]
另外当第一次输后，再次打开还是第一次输入的值，重新打开搜索框应该置空。

**Comment by ProDog** [comment]
Swap 页面还输入还在右边

![image](https://user-images.githubusercontent.com/12728872/158927140-4e3ed273-ac0e-4c71-b099-51bc6b27cf4e.png)
