### ISSUE TITLE
【V】这个页面要不要给 删除 按钮？

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#218]
现状：输错了私钥后，没有删除”x“ 按钮
期待：建议给一个删除按钮。
![截屏2022-03-16 11 10 17](https://user-images.githubusercontent.com/39148294/158509159-51aadf35-cabb-42d4-a123-77747dcb4a67.png)

**Comment by xie-yue** [comment]
浏览器可以用键盘的全选，感觉没有必要

**Comment by sunjeon** [comment]
经讨论后 关闭本需求。
