### ISSUE TITLE
【V】地址簿重复添加应该有反馈

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#219]
现状：在添加地址簿处，添加2个一样的地址。没有报错，也没有反馈。
期待：报错 address already existed
![截屏2022-03-16 15 13 03](https://user-images.githubusercontent.com/39148294/158536064-8828de34-501e-40a9-a3eb-cd2926f64d3f.png)

**Comment by ProDog** [comment]
现在页面在左边，提示在中间，调整一下就可以：

![image](https://user-images.githubusercontent.com/12728872/158934770-e02e36d3-c864-490d-9df6-e2ff602c14ac.png)
