### ISSUE TITLE
【V】loading页面细节补充

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#220]
现状：NFT -》loading时页面为空
期待：加个loading icon

https://user-images.githubusercontent.com/39148294/158537021-c229cfe8-1b28-4feb-bd94-ce022de75f6b.mp4

**Comment by ProDog** [comment]
有转圈了

![image](https://user-images.githubusercontent.com/12728872/158934536-f7ffeae1-8c42-4cf5-bffc-18824c8d07b1.png)
