### ISSUE TITLE
【V】loading应该改成loading，No data应该是loading完没有数据展示

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#221]
现状：有NFT数据，但是页面展示no data 提醒
期待：有NFT数据，在loading中应该展示loading icon。

https://user-images.githubusercontent.com/39148294/158537352-e358da22-5097-4928-b8cc-a5ac1de5b3cc.mp4

**Comment by ProDog** [comment]
现在变成两个圈圈了：

![image](https://user-images.githubusercontent.com/12728872/159423895-8a31b7ff-50ab-44de-9aa8-edfea13b1ed8.png)
