### ISSUE TITLE
钱包管理页面，UX建议

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#24]
钱包管理页面，当没有钱包的时候，会显示创建和导入钱包

![image](https://user-images.githubusercontent.com/6295602/126766441-17024aff-5a50-4236-9e5c-47e219961082.png)

点击右上角加号后，还是创建和导入钱包：

![image](https://user-images.githubusercontent.com/6295602/126766470-02ddf899-dfad-4cec-8391-2b2ef4be1a2b.png)

所以这个加号是不是多余了，建议在没有钱包的时候隐藏该按钮

**Comment by yating-900** [comment]
<img width="375" alt="Manage Wallet - Empty" src="https://user-images.githubusercontent.com/15194857/126926976-6718f7dc-e3ed-45d1-9180-4731e480aed7.png">
钱包为空状态下，“Manage Wallet”页面改成这样

**Comment by chenzhitong** [comment]
![image](https://user-images.githubusercontent.com/6295602/127104328-9f5eb158-7d25-4a5d-896d-baea9396bf3a.png)

已修复，但跟设计稿比多了个按钮
