### ISSUE TITLE
转账界面，输入金额的对话框中小数点最好作为一个按钮显示，以便于更好的交互

### ISSUE THREAD

**Issue by RookieCoderrr** [steven1227/MovieDB#26]

**Comment by RookieCoderrr** [comment]
![image](https://user-images.githubusercontent.com/86407596/126767019-6def5399-b9cb-47e3-a6b4-f2279adecdec.png)

**Comment by RookieCoderrr** [comment]
ios 系统

**Comment by xie-yue** [comment]
系统键盘自带的UI，无法修复
