### ISSUE TITLE
助记词导入钱包，UI建议

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#27]
这个输入框太高了，助记词占2行，如果输入框高度小一点，下面按钮正好能显示全。

![image](https://user-images.githubusercontent.com/6295602/126766824-d692973d-53d4-4f0b-a6be-7764ce61b910.png)

**Comment by xie-yue** [comment]
添加了点击输入框外关闭键盘的功能

**Comment by sunjeon** [comment]
ok。
