### ISSUE TITLE
【安卓】搜索栏

### ISSUE THREAD

**Issue by descartes100** [steven1227/MovieDB#3]
![Inked2_LI](https://user-images.githubusercontent.com/56905512/126756798-d3d3b289-f496-43e8-ac4b-79d673363188.jpg)
1. 没有搜索键，且搜索没有结果。
2. “>”键的功能是扫描二维码，建议换成“[-]”比较明显的图标或者增加说明。

**Comment by sunjeon** [comment]
这个页面还没有开发～
