### ISSUE TITLE
【iOS】在Manage Asset添加新token后，Wallet页面和Send中Select Asset页面均无显示新添加的Token

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#31]
![image](https://user-images.githubusercontent.com/87798080/126767501-a23bdf62-42ae-4673-9d48-6d674d5c5012.png)
![image](https://user-images.githubusercontent.com/87798080/126767513-a952fa6a-f346-4d66-be2f-2d5f65a06cc8.png)
![image](https://user-images.githubusercontent.com/87798080/126767539-94b718a4-3587-4eb7-8780-fdd9732d147e.png)

**Comment by xie-yue** [comment]
home已修正，send话没有资产不会显示

**Comment by sunjeon** [comment]
糯米确认已修复。
