### ISSUE TITLE
Bug 填写转账金额时崩溃

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#32]
https://user-images.githubusercontent.com/6295602/126767599-d7ae509c-9161-4d38-b2ef-087e8c2d3a45.mp4

不知道是不是余额为0的原因，我在转账金额里输入金额，删除金额的时候，都会崩溃

**Comment by chenzhitong** [comment]
![image](https://user-images.githubusercontent.com/6295602/126767742-75d2ebab-06c7-4ce3-85c0-f7e4e230a27b.png)

**Comment by sunjeon** [comment]
前端修改点击按钮的权限控制。必须所有输入框都输入，才允许“转账”按钮高亮
