### ISSUE TITLE
已有钱包的情况下，创建/导入新的钱包不需要密码验证

### ISSUE THREAD

**Issue by yating-900** [steven1227/MovieDB#34]

**Comment by xie-yue** [comment]
@sunjeon 
导入新钱包需要密码认证啊

**Comment by yating-900** [comment]
@xie-yue @sunjeon 
做用户测试的时候，被测者表示导入钱包之后输入密码很让他困惑，不懂为啥这时候要输入密码。解决方案（已有钱包的情况下）：
1. 创建/导入新钱包，不需要密码认证
2.  把密码认证提前到创建/导入新钱包的流程之前。跟查看私钥/助记词类似。

**Comment by sunjeon** [comment]
@xie-yue  @yating-900 

不需要密码验证。

已有钱包的情况下，表示用户已经拥有了一个全局通用的密码。而且，在密码为全局统一密码时，让用户设置多个密码，是不是又变成了一个钱包一个密码的操作？改密码的作用是：验证在app的行为是操作者本人。

如果是有过钱包，全部删掉，再重新创建第一个钱包的前提下，则需要创建新的钱包。

总结：密码总是跟着第一个钱包生成。

**Comment by xie-yue** [comment]
@sunjeon 创建第二个以后的钱包，并不是创建密码，而是验证密码，保证创建动作是本人执行

**Comment by steven1227** [comment]
> @sunjeon 创建第二个以后的钱包，并不是创建密码，而是验证密码，保证创建动作是本人执行

已经测试。确实如此。但是此处需要有个UI改进感觉。在wallet页面没有明显显示钱包名的地方。 @yating-900

**Comment by sunjeon** [comment]
已解决。
