### ISSUE TITLE
页面滚动条未隐藏

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#35]
这个页面的滚动条应该隐藏，而且滚动的范围是：my assets的范围滚动；popular asset的范围滚动。

当前状况：整个页面一起滚动。
![585CE108-E7A8-4DF2-9A16-AF9F3F4353B9](https://user-images.githubusercontent.com/39148294/126925143-d2114dca-d6ac-45c0-aa4a-a3a80b1a7107.png)

**Comment by xie-yue** [comment]
分成两个滚动部分的话需要给出两个列表的显示范围，目前my asset是不固定的，popular最大10条 @sunjeon

**Comment by sunjeon** [comment]
@yating-900 确定一下吧。

**Comment by yating-900** [comment]
整个页面滚动可以的。
如果第一个list过长，用户可以选择折叠my assets，不影响体验。

**Comment by sunjeon** [comment]
那滚动条是隐藏还是现在这样？

我怎么感觉如果是在白色区域内滚动，则是在2个不同区域滚动。在公共区域上滑下滑，才是整屏滑动？

**Comment by yating-900** [comment]
滚动条可以保留，方便用户知道自己在list的哪个地方。
但细节需要优化下（滚动条位置需更靠右一些，离右边缘8px左右就可以）

**Comment by yating-900** [comment]
这个我补充到细节合集里啦，可以close了
