### ISSUE TITLE
搜索排序优化

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#36]
状况描述：搜索e，下方最匹配的应该是fWETH。但实际不是。

功能预期：代币优先、合约其次

![45439196-2882-4DB6-89E9-EA6B3401BA6E](https://user-images.githubusercontent.com/39148294/126925338-1ee6baaf-a48b-42f8-8954-2b9efe553d3a.png)

**Comment by xie-yue** [comment]
设计稿给的是匹配symbol和hash，需要明确一些匹配规则 @sunjeon

**Comment by sunjeon** [comment]
嗯。是symbol和hash。但是要继续细分symbol是怎么排序的。
顺序如下：
1. 输入字母或数字优先匹配symbol；symbol全部找完了，匹配hash。
2. 匹配symbol是按照字母的先后顺序进行排序。
如：e/E
（假设为垮链）则顺序为：
1.1 ENJ、EOS、ETH...
1.2 esjskiaopap123、aedjsjaooa1839、bedhdisiiw2828

**Comment by sunjeon** [comment]
还有一些需要改的部分。

1. 当前的排序规则：

symbol：NEO，hash：0xe1
symbol：GAS，hash：0xen
symbol：ABN，hash：0x3n

- 当搜索了n，symbol结果会有NEO和ABN，hash的结果有GAS和ABN。
- 返回的结果依次为：1.NEO    2.ABN    3.GAS（0xen）

2.需要改的部分：需要按照symbol的字母顺序依次匹配。

symbol：WETH；
symbol：WATH；
symbol：AWETH

- 当搜索了w，
- 返回的结果依次为：1.WATH    2.WETH   3.AWETH

**Comment by sunjeon** [comment]
已验证
