### ISSUE TITLE
ui需要调整

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#38]
如图红色圈出来的部分，看起来有点奇怪。

![821627351622_ pic](https://user-images.githubusercontent.com/39148294/127083788-eef4d8ae-77f5-4e10-b9bc-9dcbfe027965.jpg)
![811627351618_ pic](https://user-images.githubusercontent.com/39148294/127083791-d31d3879-8820-400f-b7a1-73614026744e.jpg)

**Comment by yating-900** [comment]
行高需要定义一下，参考figma的style guides图。
单行行高：48px，
双行行高：64px.
