### ISSUE TITLE
安卓钱包余额显示

### ISSUE THREAD

**Issue by leiw5173** [steven1227/MovieDB#4]
安卓用户，钱包余额显示$320，但无NEO和GAS数量显示。
![image](https://user-images.githubusercontent.com/73590328/126757238-75e90216-e52f-4f9b-b56d-9c7cb2fa860d.png)

**Comment by leiw5173** [comment]
华为P40

**Comment by sunjeon** [comment]
320为mock数据。 请问是否实际有收到存款？

若没有收到aesset，则目前的展示是正确的。

**Comment by leiw5173** [comment]
> 320为mock数据。 请问是否实际有收到存款？
> 
> 若没有收到aesset，则目前的展示是正确的。

没有收到asset。

**Comment by sunjeon** [comment]
那就是正确的。我关闭issue了
