### ISSUE TITLE
细节-Address Book 没有分开

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#40]
应该要分开：Address Book
![881627353958_ pic](https://user-images.githubusercontent.com/39148294/127087158-f02e6921-be37-4875-9b80-e9750c87c123.jpg)
![截屏2021-07-27 上午10 46 34](https://user-images.githubusercontent.com/39148294/127087174-e7688601-197e-400c-be5b-9666c06b3d4c.png)

**Comment by yating-900** [comment]
这个我放到ui细节合集里了，可以close

**Comment by sunjeon** [comment]
已验证
