### ISSUE TITLE
细节-转账二次确认没有显示备注信息。

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#42]
如图：我已将该地址保存至地址簿，且命名为：糯。
但是在转账的二次确认页面没有看到这个备注信息。

![951627355222_ pic](https://user-images.githubusercontent.com/39148294/127089056-034bfa2d-2934-42e6-9032-dcadd56591e0.jpg)

![941627355201_ pic](https://user-images.githubusercontent.com/39148294/127089047-81e08ae0-d131-45c6-ab3c-fb9245da5069.jpg)

**Comment by yating-900** [comment]
这里需要做个判断：
如果address在地址簿里，则显示remark。
如果address不在地址薄里，则不显示任何remark。

**Comment by xie-yue** [comment]
@yating-900 UI的设计稿有么？

**Comment by yating-900** [comment]
> @yating-900 UI的设计稿有么？

<img width="1047" alt="Screenshot 2021-07-28 at 10 27 10" src="https://user-images.githubusercontent.com/15194857/127253930-db3714f3-b840-4cb4-b899-10a5df4b1ac7.png">

**Comment by sunjeon** [comment]
Records里面的详情页也需要这个。

**Comment by sunjeon** [comment]
已解决
