### ISSUE TITLE
【iOS】Send页面中Select Asset弹窗中，点选输入框后键盘弹出遮住弹窗。

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#43]
![image](https://user-images.githubusercontent.com/87798080/127089372-90466ea4-4fe9-4329-8d15-3972168d71e6.png)
![image](https://user-images.githubusercontent.com/87798080/127089384-61b0092d-516b-4a03-892e-f4ed6e014b28.png)

**Comment by steven1227** [comment]
安卓小米10测试已经没有此问题。IOS需要再测下。

**Comment by FamelessLeo** [comment]
iOS尚未解决，键盘依旧遮盖弹窗，麻烦再修复一下～
![image](https://user-images.githubusercontent.com/87798080/127252501-dd7e07e0-8d12-451d-b2c9-a25fa150c1ac.png)

**Comment by sunjeon** [comment]
已验证
