### ISSUE TITLE
【iOS】没有gas的情况下转账NEO，警告应是【Insufficient Gas】

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#44]
![image](https://user-images.githubusercontent.com/87798080/127089668-ea165464-a772-4d92-9318-c65443634c4c.png)

**Comment by sunjeon** [comment]
同意。

提示语：Insufficient GAS（NEO transaction costs GAS） / GAS代币不足（Neo转账需要支付GAS代币）

**Comment by steven1227** [comment]
这个确实是一个问题。我没有GAS或者GAS不够的情况下，不应该让用户还能一路操作下去。当条件充分满足时，应该提早disable continue。

**Comment by xie-yue** [comment]
这个需要执行转账的时候计算手续费，无法警告disable转账按钮

**Comment by FamelessLeo** [comment]
已修正！
