### ISSUE TITLE
GAS费没有预估

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#49]
![961627356636_ pic](https://user-images.githubusercontent.com/39148294/127090924-03c73cf8-33ec-4196-93d5-2a8943432936.jpg)

**Comment by steven1227** [comment]
安卓上还有这个问题。显示还都是0

**Comment by sunjeon** [comment]
ios也没有解决。也是0

**Comment by sunjeon** [comment]
ios上还是0

**Comment by steven1227** [comment]
目前这个地方似乎只统计了用户添加的网络费。

**Comment by xie-yue** [comment]
已添加

**Comment by sunjeon** [comment]
已验证。
