### ISSUE TITLE
转账点击金额，小键盘会把页面往上顶导致无法显示输入的金额

### ISSUE THREAD

**Issue by superboyiii** [steven1227/MovieDB#5]
![image](https://user-images.githubusercontent.com/38493437/126758362-3a275e60-0931-4b3b-8bae-2f7e4899f0c2.png)
Android HUAWEI P30

**Comment by steven1227** [comment]
小米 +1

**Comment by xie-yue** [comment]
修正了键盘使页面调整的问题

**Comment by sunjeon** [comment]
ios已验证修正。

**Comment by steven1227** [comment]
小米10已验证修正。
