### ISSUE TITLE
【iOS】自己给自己转账NEO，Records中仅有转出记录，没有转入记录

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#50]
![image](https://user-images.githubusercontent.com/87798080/127101779-7e976f5b-dbe1-4505-a03e-1bd632fc72c5.png)
![image](https://user-images.githubusercontent.com/87798080/127101829-5778cca4-b732-43da-89f1-f723de833e22.png)

**Comment by yating-900** [comment]
这种自己给自己转账，type算send还是receive啊？
@sunjeon

**Comment by sunjeon** [comment]
那应该有两条记录。一条send。一条receive

**Comment by steven1227** [comment]
这个问题确实存在。而且允许自己给自己转。如果方便处理的话按照以上 `那应该有两条记录。一条send。一条receive`  如果不方便处理，暂时按现有只显示转出也行。

**Comment by FamelessLeo** [comment]
自己给自己转账，目前已显示sen d和发送两条记录，但应当先显示send（即-50）的记录，再显示receive（+50）记录
![image](https://user-images.githubusercontent.com/87798080/127475981-5f838450-00ee-483d-8763-106fa2b1d5ff.png)

**Comment by FamelessLeo** [comment]
已修复！
