### ISSUE TITLE
钱包详情，查看助记词，输入错误的密码后……

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#54]
正确密码 12345678
输入正确密码，显示正确助记词
输入错误密码 123456789
显示了一个奇怪的页面

https://user-images.githubusercontent.com/6295602/127112011-fa1a0894-72c0-4244-bf53-4818520fdbce.mp4

**Comment by chenzhitong** [comment]
https://user-images.githubusercontent.com/6295602/127112471-5a790dfc-70cf-440e-9d5c-16beaf23629a.mp4

还有一个Bug，输入错误密码`111111114`和错误密码`000000000`，点`Confirm`按钮后没反应，不显示密码错误。

**Comment by sunjeon** [comment]
我输入1，-》点击confirm-〉也没有任何的报错

**Comment by steven1227** [comment]
刚测试了一下，输入错误密码会报错。需要继续不同机型和条件下多次测试。

**Comment by sunjeon** [comment]
我报告的这个错误现在已经修复 （issue内容：我输入1，-》点击confirm-〉也没有任何的报错）

**Comment by chenzhitong** [comment]
>  da59e3d9de0bf29f69c46ca6de36f59e.mp4 
> 还有一个Bug，输入错误密码`111111114`和错误密码`000000000`，点`Confirm`按钮后没反应，不显示密码错误。

这个修复了，第一个（输入某些特定错误密码进入一个奇怪的页面的那个）还没修复

**Comment by chenzhitong** [comment]
Release 29 已修复
