### ISSUE TITLE
【iOS】通过助记词import钱包，输入助记词后键盘无法下滑，无法点击“Import Wallet”

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#6]
![image](https://user-images.githubusercontent.com/87798080/126758309-4f9f9b82-fbbd-4337-bedc-14824be6b71f.png)
![111627029929_ pic](https://user-images.githubusercontent.com/87798080/126758827-73dd7ec8-3692-45fd-aaff-580e761e9d5b.jpg)

**Comment by FamelessLeo** [comment]
![111627029929_ pic](https://user-images.githubusercontent.com/87798080/126758643-02f66e86-0d69-4c62-a206-6b0da1d8b0c5.jpg)

**Comment by xie-yue** [comment]
添加了点击输入框外关闭键盘的功能

**Comment by sunjeon** [comment]
糯米确认已修复
