### ISSUE TITLE
找了好久才找到 Address Book 的编辑和删除功能

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#61]
找了好久才找到 Address Book 的编辑和删除功能，
之前试了点击，长按，都不好使，准备提Issue了，去Figma里看，才知道是左滑可以编辑和删除
能否在Add Address后给一些动画提示 @yating-900

**Comment by yating-900** [comment]
ok，这个issue添加到了细节优化合集 #46 
增加了个交互，点击list item整行可以进入编辑页面。

<img width="1002" alt="Screenshot 2021-07-28 at 11 47 08" src="https://user-images.githubusercontent.com/15194857/127269341-17636e23-4435-41e9-bbb9-b2377f4205e1.png">

**Comment by xie-yue** [comment]
@yating-900 需要讨论

**Comment by yating-900** [comment]
修改后的设计稿，ok吗
<img width="707" alt="Screenshot 2021-07-28 at 14 15 49" src="https://user-images.githubusercontent.com/15194857/127273193-ebf3ee82-07f6-4d1f-b3b9-ba72f455d235.png">

**Comment by sunjeon** [comment]
我觉得藏得太深了。2步能点完的现在要3个步骤了。看不到必要性？

**Comment by yating-900** [comment]
> 我觉得藏得太深了。2步能点完的现在要3个步骤了。看不到必要性？

edit和delete操作其实不是很经常，多个步骤影响不大。

（上一版的点整行的设计稿不可行，是因为点击整行的操作已经有了，就是send的时候选择address）

**Comment by sunjeon** [comment]
哦 那行吧～
