### ISSUE TITLE
导入错误私钥会显示”Mnemonic Validate Failed.“

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#63]
导入错误私钥会显示”Mnemonic Validate Failed.“

建议改为 ”Private Key Validate Failed.“ 

![image](https://user-images.githubusercontent.com/6295602/127259934-4993c085-dd21-4b21-8b55-8cfaf18eeaa3.png)

**Comment by sunjeon** [comment]
同57#。
