### ISSUE TITLE
资产图标在本地有缓存，不能及时更新

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#64]
请求过的资产图标，如果服务器端有修改，就不会更新，可能本地有缓存。

我先上传了个是白色背景的 FLM，然后又在服务器端修改为透明背景

资产列表的图片保持不变（旧的图标）

![image](https://user-images.githubusercontent.com/6295602/127302873-02d6be1b-704e-458e-b689-28c5543c34ac.png)

另一个用户第一次请求 FLM 图标的，就会正常显示（新的图标）

![image](https://user-images.githubusercontent.com/6295602/127303018-11e61e94-e08a-4b4c-8488-9a427c1bde8b.png)

**Comment by chenzhitong** [comment]
另外，NEO、GAS、Default 图标，在服务器上也更新了（修改为正方形图片），由于客户端有缓存，也不会更新

**Comment by yating-900** [comment]
以及一个小细节，有的资产图标被裁减了
