### ISSUE TITLE
交易无转账记录 安卓 华为P40

### ISSUE THREAD

**Issue by leiw5173** [steven1227/MovieDB#65]
![image](https://user-images.githubusercontent.com/73590328/127451715-95e7bd66-e6bd-4810-8c99-32ce4a9835f0.png)
![image](https://user-images.githubusercontent.com/73590328/127451746-0d09c994-481b-42bb-b72d-d9d59ef5849f.png)

**Comment by xie-yue** [comment]
服务器问题，并且空页面添加了下拉刷新
