### ISSUE TITLE
【iOS】自己给自己转账，send和receive记录顺序应对换

### ISSUE THREAD

**Issue by FamelessLeo** [steven1227/MovieDB#68]
自己给自己转账，目前已显示send和receive两条记录，但应当先显示send（即-50的记录在下），再显示receive（+50的记录在上）
![image](https://user-images.githubusercontent.com/87798080/127476518-681c02d1-b353-4571-adff-2878716e5676.png)

**Comment by sunjeon** [comment]
还是老样子～
![1141627614945_ pic](https://user-images.githubusercontent.com/39148294/127594533-8d7ffcd2-50aa-4d82-8060-c5d1c2391e7a.jpg)

**Comment by sunjeon** [comment]
已验证。
