### ISSUE TITLE
转出交易展示的type为receive

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#71]
这是一笔send给自己的交易。

当前状况：type应该识别为receive
功能预期：type应该识别为send。

![1131627614815_ pic](https://user-images.githubusercontent.com/39148294/127594361-50c65ebc-f0ba-4983-9d4c-96e1dd278885.jpg)

**Comment by steven1227** [comment]
我测试了一下好像已经事send了。

**Comment by sunjeon** [comment]
昂？ 发新版本了？早些下午给谢越展示的时候还是receive呢

**Comment by sunjeon** [comment]
已验证。
