### ISSUE TITLE
转账记录的顺序变更

### ISSUE THREAD

**Issue by sunjeon** [steven1227/MovieDB#72]
当前状况：先收到reward，在转出记录
功能预期：先转出，再收到reward

![1161627616725_ pic](https://user-images.githubusercontent.com/39148294/127597055-8958078e-a1ac-45c3-8cfb-7501a8304b5f.jpg)

**Comment by steven1227** [comment]
问题确实存在。可能需要后端修改

**Comment by xie-yue** [comment]
![Simulator Screen Shot - iPhone 12 - 2021-08-02 at 09 59 20](https://user-images.githubusercontent.com/1343752/127794700-25aee5b9-3bd2-4146-afc2-73adc6ae1b9f.png)

**Comment by xie-yue** [comment]
已修复

**Comment by sunjeon** [comment]
已验证/

**Comment by sunjeon** [comment]
好神奇，我刚在最新版本上验证了一下，发现又不对了。
![1211627887448_ pic](https://user-images.githubusercontent.com/39148294/127817303-a50ef21b-96ff-42c4-9c25-2a1ce2e5088a.jpg)
