### ISSUE TITLE
安卓上，底部导航栏的按钮样式错误

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#75]
![15fce060b1b7751a03be4f8ef328b2d](https://user-images.githubusercontent.com/6295602/129660409-0a30e12b-e912-496a-95e8-84e7be26dc3b.jpg)

**Comment by sunjeon** [comment]
图片上的 $0 也很奇怪。

**Comment by chenzhitong** [comment]
Fixed
