### ISSUE TITLE
 BUG Asset 添加后 ，Wallet页面无变化

### ISSUE THREAD

**Issue by WSbaikaishui** [steven1227/MovieDB#8]
#### 安卓 小米11  张耀文
![Screenshot_2021-07-23-16-35-48-576_com onegate](https://user-images.githubusercontent.com/46080358/126758607-995a925c-2a3c-44fd-822a-8124bb04ae91.jpg)

**Comment by sunjeon** [comment]
这个的问题是：它地址上可以查到assets的余额，但是钱包里面没有。
