### ISSUE TITLE
改进 时间选择器  

### ISSUE THREAD

**Issue by WSbaikaishui** [steven1227/MovieDB#9]
#### 安卓  小米11
![Screenshot_2021-07-23-16-38-43-580_com onegate](https://user-images.githubusercontent.com/46080358/126758842-08b6ba22-217c-4efd-aecd-991806ea4161.jpg)

**Comment by sunjeon** [comment]
且ios 苹果X机型下，日期为2行展示。与设计稿展示的不同。
![751627032533_ pic](https://user-images.githubusercontent.com/39148294/126763357-d362871f-8ce3-4db4-9833-1bdd9f23d839.jpg)

**Comment by xie-yue** [comment]
修复了两行显示的问题

**Comment by sunjeon** [comment]
已修复。
