### ISSUE TITLE
NFT页面UI的小问题

### ISSUE THREAD

**Issue by chenzhitong** [steven1227/MovieDB#93]
图片显示不全，被截断了

滚动部分的高度不太对，导致下面有空白

![ed91e47f863dd62a76511ed2e686e4e](https://user-images.githubusercontent.com/6295602/129833773-5b8a04ee-14bd-4ec3-8bcc-c2a499927b45.jpg)

**Comment by yating-900** [comment]
缩略图都是按固定长宽比截取，如果每个nft的长宽比不一样，截取的效果不一样...
要是长的nft比较普遍的话，这个缩略图的长宽比也可以调整一下
